on:
  schedule:
    - cron: "*/1 * * * *"

name: keyvault_test

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0

      
    - name: Az_login  
      uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
    
    - name: Run_script
      run: |
         chmod +x ./.github/workflows/key.sh
         ./.github/workflows/key.sh
      shell: bash   
    
#     - name: Run_script2
#       run: |
#          ./key_vault.sh
         
